name: Run tests on CI

on: [workflow_dispatch, pull_request, push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test
