name: Build DIRECTORY.md
on: [push, pull_request]

jobs:
  main:
    name: Update DIRECTORY.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Update DIRECTORY.md file
        run: |
          wget https://raw.githubusercontent.com/TheAlgorithms/scripts/main/build_directory_md.py
          python3 build_directory_md.py Zig . .zig build.zig > DIRECTORY.md
      - name: Commit changes
        run: |
          git diff
          git commit -m "Update DIRECTORY.md" DIRECTORY.md || true
          git push --force origin HEAD:$GITHUB_REF || true

