---
name: clojure_test

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  clojure_test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        clojure_version:
          - "1.10.3.1029"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: ${{matrix.clojure_version}}

      - name: Run tests
        run: |
          clojure -X:test
...
