language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run lint
  - npm run format
  - npm run test:coverage
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search